### ISSUE TITLE
Убрать меню персонажа из выбора классов

### ISSUE THREAD

**Issue by Dasem** [Dasem/textGame#26]

**Comment by w3st125** [comment]
Просто добавил настройку в меню выбора специализации

**Comment by Dasem** [comment]
|       |		  |
Имя     | Класс | Уровень |
________|_______|_________|


        |       |		  	   |
ХП      |Золото | Опыт/Уровень |
________|_______|______________|

           |       		  |
Броня      |Оружие/Урон   |
___________|______________|

**Comment by Dasem** [comment]
![image](https://user-images.githubusercontent.com/41896057/113590191-cbbff280-964b-11eb-8047-da2ba95f1cfe.png)

**Comment by Dasem** [comment]
Не ту реопнул
